#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr
$HOME/.fehbg &
xset s off -dpms s noblank &
pgrep -x bar.sh > /dev/null || ~/.config/bspwm/bar.sh &
